### ISSUE TITLE
Add option for json-formatted output

### ISSUE THREAD

**Issue by joelb-git** [joelb-git/lqt#5]
Add option for json-formatted output

I've become a big fan of [jq](http://stedolan.github.io/jq/).  It's great for selecting portions of a
json file.  The current default output of lqt is just "key: value"
pairs.  It wouldn't take much to turn this into json.  Json arrays
would be a more natural way to show multi-valued fields.

**Comment by yuval** [comment]
Resolved in c67e17ebd2ef7843c9d630bc3ecbf477cdf6cab7.
